#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-ipyparallel
Version  : 8.4.1
Release  : 20
URL      : https://files.pythonhosted.org/packages/6d/ce/644d81cbeeeb5bd5ba330455f393384d3389b2e1fa3703063591ba1f2054/ipyparallel-8.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/6d/ce/644d81cbeeeb5bd5ba330455f393384d3389b2e1fa3703063591ba1f2054/ipyparallel-8.4.1.tar.gz
Summary  : Interactive Parallel Computing with IPython
Group    : Development/Tools
License  : BSD-3-Clause
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
BuildRequires : pypi(ipywidgets)
BuildRequires : pypi(jupyterlab)
BuildRequires : pypi(jupyterlab_link_share)
BuildRequires : pypi(matplotlib)
BuildRequires : pypi(networkx)
BuildRequires : pypi(pidigits)
BuildRequires : pypi(requests)
BuildRequires : pypi(retrolab)
BuildRequires : pypi(wordfreq)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Interactive Parallel Computing with IPython
IPython Parallel (`ipyparallel`) is a Python package and collection of CLI scripts for controlling clusters of IPython processes, built on the Jupyter protocol.

%prep
%setup -q -n ipyparallel-8.4.1
cd %{_builddir}/ipyparallel-8.4.1
pushd ..
cp -a ipyparallel-8.4.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672932844
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ipyparallel
cp %{_builddir}/ipyparallel-%{version}/COPYING.md %{buildroot}/usr/share/package-licenses/pypi-ipyparallel/2c15eff35efcbd62ef860412b46613a6a194fbc3 || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_notebook_config.d/ipyparallel.json
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_server_config.d/ipyparallel.json
rm -f %{buildroot}*/usr/etc/jupyter/nbconfig/tree.d/ipyparallel.json
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
