#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v21
# autospec commit: f35655a
#
Name     : pypi-ipyparallel
Version  : 9.0.0
Release  : 31
URL      : https://files.pythonhosted.org/packages/d4/f6/05e91119bad61b9e10f8fdce687a93d50c372646e0a5332c19bc251faaf0/ipyparallel-9.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/d4/f6/05e91119bad61b9e10f8fdce687a93d50c372646e0a5332c19bc251faaf0/ipyparallel-9.0.0.tar.gz
Summary  : Interactive Parallel Computing with IPython
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-ipyparallel-bin = %{version}-%{release}
Requires: pypi-ipyparallel-data = %{version}-%{release}
Requires: pypi-ipyparallel-license = %{version}-%{release}
Requires: pypi-ipyparallel-python = %{version}-%{release}
Requires: pypi-ipyparallel-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
BuildRequires : pypi(ipywidgets)
BuildRequires : pypi(jupyterlab)
BuildRequires : pypi(jupyterlab_link_share)
BuildRequires : pypi(matplotlib)
BuildRequires : pypi(networkx)
BuildRequires : pypi(pidigits)
BuildRequires : pypi(requests)
BuildRequires : pypi(retrolab)
BuildRequires : pypi(wordfreq)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Interactive Parallel Computing with IPython
IPython Parallel (`ipyparallel`) is a Python package and collection of CLI scripts for controlling clusters of IPython processes, built on the Jupyter protocol.

%package bin
Summary: bin components for the pypi-ipyparallel package.
Group: Binaries
Requires: pypi-ipyparallel-data = %{version}-%{release}
Requires: pypi-ipyparallel-license = %{version}-%{release}

%description bin
bin components for the pypi-ipyparallel package.


%package data
Summary: data components for the pypi-ipyparallel package.
Group: Data

%description data
data components for the pypi-ipyparallel package.


%package license
Summary: license components for the pypi-ipyparallel package.
Group: Default

%description license
license components for the pypi-ipyparallel package.


%package python
Summary: python components for the pypi-ipyparallel package.
Group: Default
Requires: pypi-ipyparallel-python3 = %{version}-%{release}

%description python
python components for the pypi-ipyparallel package.


%package python3
Summary: python3 components for the pypi-ipyparallel package.
Group: Default
Requires: python3-core
Provides: pypi(ipyparallel)
Requires: pypi(decorator)
Requires: pypi(ipykernel)
Requires: pypi(ipython)
Requires: pypi(ipywidgets)
Requires: pypi(jupyter_client)
Requires: pypi(jupyterlab_link_share)
Requires: pypi(matplotlib)
Requires: pypi(networkx)
Requires: pypi(pidigits)
Requires: pypi(psutil)
Requires: pypi(python_dateutil)
Requires: pypi(pyzmq)
Requires: pypi(requests)
Requires: pypi(retrolab)
Requires: pypi(tornado)
Requires: pypi(tqdm)
Requires: pypi(traitlets)
Requires: pypi(wordfreq)

%description python3
python3 components for the pypi-ipyparallel package.


%prep
%setup -q -n ipyparallel-9.0.0
cd %{_builddir}/ipyparallel-9.0.0
pushd ..
cp -a ipyparallel-9.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1730910994
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ipyparallel
cp %{_builddir}/ipyparallel-%{version}/COPYING.md %{buildroot}/usr/share/package-licenses/pypi-ipyparallel/2c15eff35efcbd62ef860412b46613a6a194fbc3 || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
## Remove excluded files
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_notebook_config.d/ipyparallel.json
rm -f %{buildroot}*/usr/etc/jupyter/jupyter_server_config.d/ipyparallel.json
rm -f %{buildroot}*/usr/etc/jupyter/nbconfig/tree.d/ipyparallel.json
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ipcluster
/usr/bin/ipcontroller
/usr/bin/ipengine

%files data
%defattr(-,root,root,-)
/usr/share/jupyter/labextensions/ipyparallel-labextension/package.json
/usr/share/jupyter/labextensions/ipyparallel-labextension/schemas/ipyparallel-labextension/package.json.orig
/usr/share/jupyter/labextensions/ipyparallel-labextension/schemas/ipyparallel-labextension/plugin.json
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/296.87b6a53d1d5b3f17143e.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/remoteEntry.8bfbc894f1978b53b2e2.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/style.js
/usr/share/jupyter/labextensions/ipyparallel-labextension/static/third-party-licenses.json
/usr/share/jupyter/nbextensions/ipyparallel/clusterlist.css
/usr/share/jupyter/nbextensions/ipyparallel/clusterlist.js
/usr/share/jupyter/nbextensions/ipyparallel/main.js

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-ipyparallel/2c15eff35efcbd62ef860412b46613a6a194fbc3

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
